branches:
  only:
  - master

addons:
  apt:
    packages:
    - "python-docutils"
    - "git"

sudo: "required"

services:
- "docker"

language: "php"
php:
  - "7.0"

env:
- CLOUDSDK_PYTHON_SITEPACKAGES=1
  GIT_SSH_COMMAND="ssh -i .privkey"

# Used for modifying the Travis environment so it is suitable for CI + CD
before_install:
  # General bin
  # Path is ordered this way so we found our custom gcloud prior to travis's one.
  - "PATH=$(pwd)/bin:${PATH}"

  # Google Cloud Path
  - "PATH=$(pwd)/google-cloud-sdk/bin:${PATH}"

  # CI Scripts
  - "PATH=$(pwd)/build/scripts/CI:${PATH}"

  # Secret dismantlement
  - "unpack-secrets.sh"

  # Install build dependencies
  - "install-google-cloud.sh"
  - "curl -sL https://deb.nodesource.com/setup_5.x"
  - "sudo apt-get install -y nodejs"
  - "sudo npm install -g grunt"

  # Rebuild path
  - "hash -r"

# Used for installing application specific dependencies
install:
  - "build.sh"

# Used with the presumption all dependices could be downloaded fine, for testing
# and authorisation of various services prior to deployment
before_script:
  - "auth-gcloud.sh"
  - "auth-kube.sh"
  - "auth-docker.sh"

# Used for deployment
script:
  - "kubectl apply -f build/kubernetes"

# Used for build notification
after_success:
  #"./build/scripts/CI/success.sh"

# Used for build notification
after_failure:
  #"./build/scripts/CI/failure.sh"

# Currently unused
after_script:
