# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: m2onk8s 
email: support[at]littleman[dot]co
description: > # this means to ignore newlines until "baseurl:"
    Kubernetes is Cool. Magento 2 is cool. Maybe if we multiply them together, 
    they'll be 4x as cool! That's how math works, right?
baseurl: "/m2onk8s"
url: "http://andrewhowden.github.io/"
twitter_username: andrewhowdencom
github_username: andrewhowdencom

# Build settings
markdown: kramdown
